rm(list=ls(all=TRUE))
dat<-read.table(file="f.txt",sep=",")
#View(dat)
y<-t(dat)
#View(y)
a<-table(y)
#View(a)
f<-as.data.frame(a)
#View(f)
f[,3]<-100*as.numeric(f[,2])/(sum(as.numeric(f[,2])))
f[,4]<-cumsum(as.numeric(f[,2]))
f[,5]<-cumsum(as.numeric(f[,3]))
colnames(f)<-c("znacheiya","chastota","chastost'","nakoplennaya chastosta","nakoplennaya chastost'")
#View(f)
b<-as.numeric(dat)
#View(b)
b<-sort(b)
#View(b)
b<-unique(b)
#View(b)
f[,1]<-b
View(f)
plot(as.numeric(f[,1]),as.numeric(f[,2]),type="l",main="poligon raspr",xlab="chastota")
plot(as.numeric(f[,1]),as.numeric(f[,5]),type="l",main="kumul abs chast")
plot(as.numeric(f[,1]),as.numeric(f[,4]),type="l",main="kum otn chast")

